name: Build RustDesk Windows x64

on:
  workflow_dispatch:

env:
  RUST_VERSION: "1.75"
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"
  VCPKG_COMMIT_ID: "9e593bb18ea69cc5095e012465dcd675a822ed0d"

jobs:

  generate-bridge:
    uses: ./.github/workflows/bridge.yml

  build-RustDeskTempTopMostWindow:
    uses: ./.github/workflows/third-party-RustDeskTempTopMostWindow.yml
    with:
      upload-artifact: true
      target: windows-2022
      configuration: Release
      platform: x64
      target_version: Windows10

  build-windows:
    name: Windows x64
    needs:
      - generate-bridge
      - build-RustDeskTempTopMostWindow

    runs-on: windows-2022

    steps:

      - name: Checkout RustDesk
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore bridge files
        uses: actions/download-artifact@v4
        with:
          name: bridge-artifact
          path: ./

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: ${{ env.LLVM_VERSION }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
          architecture: x64

      - name: Replace Flutter engine
        shell: powershell
        run: |
          flutter doctor -v
          flutter precache --windows

          Invoke-WebRequest `
            -Uri https://github.com/rustdesk/engine/releases/download/main/windows-x64-release.zip `
            -OutFile windows-x64-release.zip

          Expand-Archive `
            -Path windows-x64-release.zip `
            -DestinationPath windows-x64-release

          Copy-Item `
            windows-x64-release\* `
            "C:\hostedtoolcache\windows\flutter\stable-${{ env.FLUTTER_VERSION }}-x64\bin\cache\artifacts\engine\windows-x64-release\" `
            -Force `
            -Recurse

      - name: Patch Flutter
        shell: bash
        run: |
          cp .github/patches/flutter_3.24.4_dropdown_menu_enableFilter.diff \
            $(dirname $(dirname $(which flutter)))

          cd $(dirname $(dirname $(which flutter)))

          git apply flutter_3.24.4_dropdown_menu_enableFilter.diff

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: x86_64-pc-windows-msvc
          components: rustfmt

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: windows-x64

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - name: Install vcpkg dependencies
        shell: bash
        env:
          VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static
        run: |
          "$VCPKG_ROOT/vcpkg" \
            install \
            --triplet x64-windows-static \
            --x-install-root="$VCPKG_ROOT/installed"

      - name: Build RustDesk
        shell: powershell
        run: |
          python3 .\build.py `
            --portable `
            --flutter `
            --skip-portable-pack `
            --hwcodec `
            --vram

      - name: Download RustDeskTempTopMostWindow
        uses: actions/download-artifact@v4
        with:
          name: topmostwindow-artifacts-x64
          path: ./flutter/build/windows/x64/runner/Release

      - name: Upload Windows RustDesk
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-x64
          path: flutter/build/windows/x64/runner/Release/